### ISSUE TITLE
Replaying of events giving error - ERROR akka.actor.OneForOneStrategy - None.get

### ISSUE THREAD

**Issue by balabs2** [ing-bank/baker#141]
While restarting the server with baker version 1.3.4, following error is generated repeatedly.

[OPENACCT-akka.actor.default-dispatcher-15] [] ERROR akka.actor.OneForOneStrategy - None.get
java.util.NoSuchElementException: None.get
        at scala.None$.get(Option.scala:349)
        at scala.None$.get(Option.scala:347)
        at com.ing.baker.runtime.actor.process_index.ProcessIndex.createProcessActor(ProcessIndex.scala:110)
        at com.ing.baker.runtime.actor.process_index.ProcessIndex$$anonfun$receiveRecover$1.$anonfun$applyOrElse$11(ProcessIndex.scala:292)
        at scala.collection.mutable.HashSet.foreach(HashSet.scala:78)
        at com.ing.baker.runtime.actor.process_index.ProcessIndex$$anonfun$receiveRecover$1.applyOrElse(ProcessIndex.scala:292)
        at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:34)
        at akka.persistence.Eventsourced$$anon$3$$anonfun$1.applyOrElse(Eventsourced.scala:470)
        at akka.actor.Actor.aroundReceive(Actor.scala:517)
        at akka.actor.Actor.aroundReceive$(Actor.scala:515)
        at com.ing.baker.runtime.actor.process_index.ProcessIndex.akka$persistence$Eventsourced$$super$aroundReceive(ProcessIndex.scala:77)
        at akka.persistence.Eventsourced$$anon$4.stateReceive(Eventsourced.scala:561)
        at akka.persistence.Eventsourced.aroundReceive(Eventsourced.scala:192)
        at akka.persistence.Eventsourced.aroundReceive$(Eventsourced.scala:191)
        at com.ing.baker.runtime.actor.process_index.ProcessIndex.aroundReceive(ProcessIndex.scala:77)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:527)
        at akka.actor.ActorCell.invoke(ActorCell.scala:496)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
        at akka.dispatch.Mailbox.run(Mailbox.scala:224)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

**Comment by merlijn** [comment]
This is related to the fix we did for #133 

I will close this and copy the stack trace there
