### ISSUE TITLE
Broken examples sub-project

### ISSUE THREAD

**Issue by rjacobs91** [ing-bank/baker#365]
Currently it is impossible to build and run any of the tests in the example project from master.
It is very hard to work out how to use this framework with broken examples. 
 
`com.typesafe.config.ConfigException$Missing: application.conf @ file:/home/russelljacobs/dev/baker/runtime/target/scala-2.12/multi-jvm-classes/application.conf: 30: No configuration setting found for key 'class'

	at com.typesafe.config.impl.SimpleConfig.findKeyOrNull(SimpleConfig.java:156)
	at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:174)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:188)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:193)
	at com.typesafe.config.impl.SimpleConfig.getString(SimpleConfig.java:250)
	at akka.persistence.PersistencePlugin.akka$persistence$PersistencePlugin$$createPlugin(PersistencePlugin.scala:74)
	at akka.persistence.PersistencePlugin$$anon$1.createExtension(PersistencePlugin.scala:59)
	at akka.persistence.PersistencePlugin$$anon$1.createExtension(PersistencePlugin.scala:57)
	at akka.actor.ActorSystemImpl.registerExtension(ActorSystem.scala:1006)
	at akka.actor.ExtensionId.apply(Extension.scala:79)
	at akka.actor.ExtensionId.apply$(Extension.scala:78)
	at akka.persistence.PersistencePlugin$$anon$1.apply(PersistencePlugin.scala:57)
	at akka.persistence.PersistencePlugin.pluginFor(PersistencePlugin.scala:55)
	at akka.persistence.query.PersistenceQuery.readJournalFor(PersistenceQuery.scala:53)
	at akka.persistence.query.PersistenceQuery.readJournalFor(PersistenceQuery.scala:60)
	at com.ing.baker.runtime.akka.AkkaBakerConfig$.default(AkkaBakerConfig.scala:63)
	at com.ing.baker.runtime.akka.AkkaBakerConfig$.localDefault(AkkaBakerConfig.scala:36)
	at com.ing.baker.runtime.javadsl.Baker$.akkaLocalDefault(Baker.scala:24)
	at com.ing.baker.runtime.javadsl.Baker.akkaLocalDefault(Baker.scala)
	at webshop.JWebshopRecipeTests.shouldRunSimpleInstance(JWebshopRecipeTests.java:48)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)`

**Comment by rjacobs91** [comment]
The reason the tests fail for the examples project is that the application.conf file which is imported does not contain the full configuration necessary to run the Baker. The configuration set in reference.conf under runtime module seems to be overriden
