### ISSUE TITLE
Help integration test

### ISSUE THREAD

**Issue by sb-snrg** [ing-bank/baker#749]
Hi all,

Thanks for this great library.
I need help about running "BakeryCrdSmokeTests" directly on intellij idea with minikube.
I got errors below. I need your help to execute the integration tests in the right way.

`Error connecting to http://localhost:8080 using address localhost:8080 (unresolved: false)
org.http4s.client.ConnectionFailure: Error connecting to http://localhost:8080 using address localhost:8080 (unresolved: false)
	at org.http4s.client.blaze.Http1Support.$anonfun$buildPipeline$1(Http1Support.scala:79)
	at async @ org.http4s.internal.package$.$anonfun$fromFuture$1(package.scala:132)
	at flatMap @ org.http4s.internal.package$.fromFuture(package.scala:127)
	at flatMap @ org.http4s.client.PoolManager.$anonfun$createConnection$2(PoolManager.scala:109)
	at shift @ org.http4s.client.PoolManager.$anonfun$createConnection$2(PoolManager.scala:109)
	at uncancelable @ org.http4s.client.ConnectionManager$.pool(ConnectionManager.scala:73)
	at run @ org.scalatest.concurrent.SerialExecutionContext.recRunNow(SerialExecutionContext.scala:120)
Caused by: java.net.ConnectException: Connection refused
	at java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.checkConnect(Native Method)
	at java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.finishConnect(UnixAsynchronousSocketChannelImpl.java:252)
	at java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.finish(UnixAsynchronousSocketChannelImpl.java:198)
	at java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.onEvent(UnixAsynchronousSocketChannelImpl.java:213)
	at java.base/sun.nio.ch.KQueuePort$EventHandlerTask.run(KQueuePort.java:312)
	at java.base/java.lang.Thread.run(Thread.java:834)`

**Comment by jacum** [comment]
Not sure what you're doing, exactly, can't get it from the stacktrace.

The sequence for tests on local kubernetes is like this
1 start sbt
2 project bakery-integration-tests
3 buildExampleDocker
4 test (or testOnly com.ing.bakery.smoke.BakeryUnifiedSmokeTests etc.)

Maybe minikube doesn't forward localhost 8080 to the client app? We test on docker-desktop here.

**Comment by sb-snrg** [comment]
Thanks Jacum. Docker-desktop is the good choice.
